server:
  port: 8761

spring:
  application:
    name: eureka-center
eureka:
  #刷新时间间隔
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    hostname: localhost
  server:
    # 自我保护机制
    # 当Eureka Server节点在短时间内丢失过多的客户端时（可能发送了网络故障），
    # 那么这个节点将进入自我保护模式，不再注销任何微服务，当网络故障回复后，该节点会自动退出自我保护模式。
    #自我保护模式的架构哲学是宁可放过一个，决不可错杀一千 默认true
    enable-self-preservation: false
    #可以用来修改自我保护系数（默认0.85）。
    renewal-percent-threshold: 0.85
    eviction-interval-timer-in-ms: 5000
  client:
    # 健康监测
    healthcheck:
      enabled: true
    # 是否将自己注册  默认true  集群需要开启
    register-with-eureka: false
    # 是否从其他节点拉取注册列表  单机配置false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
